# Exported from Render on 2025-05-21T01:36:27Z (MODIFICADO PARA LARAVEL)
services:
  - type: web
    name: Information-System-I  # Nombre de tu servicio
    runtime: php  # ¡Clave! Cambia de 'node' a 'php'
    repo: https://github.com/Vit537/Information-System-I
    plan: free
    region: oregon
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:W53fODFGNRksdXMP+NSryNBIbJeGUPeQDYkGPJ0m/p0=  # Usa tu key o déjalo que Render lo genere
      - key: PHP_VERSION
        value: 8.2  # Asegúrate de usar tu versión de PHP
      # Configuración de PostgreSQL (Render)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d0mdlrje5dus738ed2r0-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: domotica
      - key: DB_USERNAME
        value: delux482
      - key: DB_PASSWORD
        value: fNaTiazdPEfBRqr4DcCtGR2CzItx6NEd
      - key: PGSSLMODE
        value: require
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan optimize
      php artisan storage:link
    startCommand: php artisan serve --host=0.0.0.0 --port=${PORT}
    autoDeployTrigger: commit
version: "1"
